import { dossierTypes, type DossierType } from '../cases/types/dossierTypes';
import type { ThreadmarkDefinition } from './threadmarkTypes';

const allKnowledgeTypes = dossierTypes;
const characterOnly = ['Character'] as const satisfies readonly DossierType[];
const characterLocationOrganization = [
  'Character',
  'Location',
  'Organization',
] as const satisfies readonly DossierType[];
const placeLikeTargets = ['Location', 'Organization'] as const satisfies readonly DossierType[];
const eventTargets = ['Event'] as const satisfies readonly DossierType[];
const createdTargets = [
  'Character',
  'Organization',
  'Theory',
  'Artifact',
] as const satisfies readonly DossierType[];

function relationship(
  definition: Omit<ThreadmarkDefinition, 'category' | 'deprecated' | 'repeatable'> & {
    deprecated?: boolean;
    repeatable?: boolean;
  },
): ThreadmarkDefinition {
  return Object.freeze({
    category: 'relationship',
    deprecated: false,
    repeatable: false,
    ...definition,
  });
}

export const relationshipThreadmarks = Object.freeze([
  relationship({
    key: 'mother',
    displayName: 'Mother',
    aliases: ['mom', 'mum', 'maternal parent'],
    description: 'A Character is the mother of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'child',
    reciprocalBehavior: 'contextual',
    sortOrder: 10,
  }),
  relationship({
    key: 'father',
    displayName: 'Father',
    aliases: ['dad', 'paternal parent'],
    description: 'A Character is the father of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'child',
    reciprocalBehavior: 'contextual',
    sortOrder: 20,
  }),
  relationship({
    key: 'parent',
    displayName: 'Parent',
    aliases: ['guardian parent'],
    description: 'A Character is a parent of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'child',
    reciprocalBehavior: 'automatic',
    sortOrder: 30,
  }),
  relationship({
    key: 'daughter',
    displayName: 'Daughter',
    aliases: ['female child'],
    description: 'A Character is the daughter of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'parent',
    reciprocalBehavior: 'automatic',
    sortOrder: 40,
  }),
  relationship({
    key: 'son',
    displayName: 'Son',
    aliases: ['male child'],
    description: 'A Character is the son of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'parent',
    reciprocalBehavior: 'automatic',
    sortOrder: 50,
  }),
  relationship({
    key: 'child',
    displayName: 'Child',
    aliases: ['offspring'],
    description: 'A Character is the child of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'parent',
    reciprocalBehavior: 'automatic',
    sortOrder: 60,
  }),
  relationship({
    key: 'sister',
    displayName: 'Sister',
    aliases: ['female sibling'],
    description: 'A Character is the sister of another Character.',
    directionality: 'contextual',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'sibling',
    reciprocalBehavior: 'contextual',
    sortOrder: 70,
  }),
  relationship({
    key: 'brother',
    displayName: 'Brother',
    aliases: ['male sibling'],
    description: 'A Character is the brother of another Character.',
    directionality: 'contextual',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'sibling',
    reciprocalBehavior: 'contextual',
    sortOrder: 80,
  }),
  relationship({
    key: 'sibling',
    displayName: 'Sibling',
    aliases: ['siblings'],
    description: 'Two Characters are siblings.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'sibling',
    reciprocalBehavior: 'automatic',
    sortOrder: 90,
  }),
  relationship({
    key: 'grandmother',
    displayName: 'Grandmother',
    aliases: ['maternal grandparent', 'paternal grandparent'],
    description: 'A Character is the grandmother of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandchild',
    reciprocalBehavior: 'contextual',
    sortOrder: 100,
  }),
  relationship({
    key: 'grandfather',
    displayName: 'Grandfather',
    aliases: ['granddad'],
    description: 'A Character is the grandfather of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandchild',
    reciprocalBehavior: 'contextual',
    sortOrder: 110,
  }),
  relationship({
    key: 'grandparent',
    displayName: 'Grandparent',
    aliases: ['grand parent'],
    description: 'A Character is the grandparent of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandchild',
    reciprocalBehavior: 'automatic',
    sortOrder: 120,
  }),
  relationship({
    key: 'granddaughter',
    displayName: 'Granddaughter',
    aliases: ['female grandchild'],
    description: 'A Character is the granddaughter of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandparent',
    reciprocalBehavior: 'automatic',
    sortOrder: 130,
  }),
  relationship({
    key: 'grandson',
    displayName: 'Grandson',
    aliases: ['male grandchild'],
    description: 'A Character is the grandson of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandparent',
    reciprocalBehavior: 'automatic',
    sortOrder: 140,
  }),
  relationship({
    key: 'grandchild',
    displayName: 'Grandchild',
    aliases: ['grand child'],
    description: 'A Character is the grandchild of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'grandparent',
    reciprocalBehavior: 'automatic',
    sortOrder: 150,
  }),
  relationship({
    key: 'aunt',
    displayName: 'Aunt',
    aliases: ['auntie'],
    description: 'A Character is the aunt of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'niece',
    reciprocalBehavior: 'contextual',
    sortOrder: 160,
  }),
  relationship({
    key: 'uncle',
    displayName: 'Uncle',
    aliases: ['uncle figure'],
    description: 'A Character is the uncle of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'nephew',
    reciprocalBehavior: 'contextual',
    sortOrder: 170,
  }),
  relationship({
    key: 'niece',
    displayName: 'Niece',
    aliases: ['female nibling'],
    description: 'A Character is the niece of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'aunt',
    reciprocalBehavior: 'contextual',
    sortOrder: 180,
  }),
  relationship({
    key: 'nephew',
    displayName: 'Nephew',
    aliases: ['male nibling'],
    description: 'A Character is the nephew of another Character.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'uncle',
    reciprocalBehavior: 'contextual',
    sortOrder: 190,
  }),
  relationship({
    key: 'cousin',
    displayName: 'Cousin',
    aliases: ['cousins'],
    description: 'Two Characters are cousins.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'cousin',
    reciprocalBehavior: 'automatic',
    sortOrder: 200,
  }),
  relationship({
    key: 'romanticPartner',
    displayName: 'Romantic Partner',
    aliases: ['partner'],
    description: 'Two Characters share a romantic relationship.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'romanticPartner',
    reciprocalBehavior: 'automatic',
    sortOrder: 300,
  }),
  relationship({
    key: 'spouse',
    displayName: 'Spouse',
    aliases: ['husband', 'wife', 'married partner'],
    description: 'Two Characters are spouses.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'spouse',
    reciprocalBehavior: 'automatic',
    sortOrder: 310,
  }),
  relationship({
    key: 'formerPartner',
    displayName: 'Former Partner',
    aliases: ['ex partner', 'former romantic partner'],
    description: 'Two Characters were formerly romantically involved.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'formerPartner',
    reciprocalBehavior: 'suggested',
    sortOrder: 320,
  }),
  relationship({
    key: 'betrothed',
    displayName: 'Betrothed',
    aliases: ['fiance', 'fiancee', 'promised spouse'],
    description: 'Two Characters are promised or engaged to one another.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'betrothed',
    reciprocalBehavior: 'automatic',
    sortOrder: 330,
  }),
  relationship({
    key: 'lover',
    displayName: 'Lover',
    aliases: ['beloved'],
    description: 'Two Characters are lovers.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'lover',
    reciprocalBehavior: 'automatic',
    sortOrder: 340,
  }),
  relationship({
    key: 'friend',
    displayName: 'Friend',
    aliases: ['friends'],
    description: 'Two Dossiers are connected as friends.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'friend',
    reciprocalBehavior: 'automatic',
    sortOrder: 400,
  }),
  relationship({
    key: 'ally',
    displayName: 'Ally',
    aliases: ['allies'],
    description: 'Two Dossiers are aligned in purpose or action.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'ally',
    reciprocalBehavior: 'automatic',
    sortOrder: 410,
  }),
  relationship({
    key: 'enemy',
    displayName: 'Enemy',
    aliases: ['foe', 'adversary'],
    description: 'Two Dossiers are opposed or hostile.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'enemy',
    reciprocalBehavior: 'suggested',
    sortOrder: 420,
  }),
  relationship({
    key: 'rival',
    displayName: 'Rival',
    aliases: ['competitor'],
    description: 'Two Dossiers are rivals.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'rival',
    reciprocalBehavior: 'automatic',
    sortOrder: 430,
  }),
  relationship({
    key: 'acquaintance',
    displayName: 'Acquaintance',
    aliases: ['known contact'],
    description: 'Two Characters know one another without a stronger defined relationship.',
    directionality: 'symmetric',
    validSourceTypes: characterOnly,
    validTargetTypes: characterOnly,
    inverse: 'acquaintance',
    reciprocalBehavior: 'automatic',
    sortOrder: 440,
  }),
  relationship({
    key: 'companion',
    displayName: 'Companion',
    aliases: ['travelling companion'],
    description: 'Two Dossiers are companions or closely associated in action.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'companion',
    reciprocalBehavior: 'automatic',
    sortOrder: 450,
  }),
  relationship({
    key: 'mentor',
    displayName: 'Mentor',
    aliases: ['guide'],
    description: 'A Dossier mentors another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'student',
    reciprocalBehavior: 'automatic',
    sortOrder: 500,
  }),
  relationship({
    key: 'student',
    displayName: 'Student',
    aliases: ['mentee'],
    description: 'A Dossier is guided by a mentor.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'mentor',
    reciprocalBehavior: 'automatic',
    sortOrder: 510,
  }),
  relationship({
    key: 'teacher',
    displayName: 'Teacher',
    aliases: ['instructor'],
    description: 'A Dossier teaches another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'apprentice',
    reciprocalBehavior: 'automatic',
    sortOrder: 520,
  }),
  relationship({
    key: 'apprentice',
    displayName: 'Apprentice',
    aliases: ['trainee'],
    description: 'A Dossier learns from a teacher.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'teacher',
    reciprocalBehavior: 'automatic',
    sortOrder: 530,
  }),
  relationship({
    key: 'leader',
    displayName: 'Leader',
    aliases: ['leads'],
    description: 'A Dossier leads another Dossier.',
    directionality: 'directional',
    validSourceTypes: characterLocationOrganization,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'member',
    reciprocalBehavior: 'automatic',
    sortOrder: 540,
  }),
  relationship({
    key: 'member',
    displayName: 'Member',
    aliases: ['member under leader'],
    description: 'A Dossier is a member under a leader.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: characterLocationOrganization,
    inverse: 'leader',
    reciprocalBehavior: 'automatic',
    sortOrder: 550,
  }),
  relationship({
    key: 'commander',
    displayName: 'Commander',
    aliases: ['commands'],
    description: 'A Dossier commands another Dossier.',
    directionality: 'directional',
    validSourceTypes: characterLocationOrganization,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'subordinate',
    reciprocalBehavior: 'automatic',
    sortOrder: 560,
  }),
  relationship({
    key: 'subordinate',
    displayName: 'Subordinate',
    aliases: ['under command'],
    description: 'A Dossier is subordinate to another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: characterLocationOrganization,
    inverse: 'commander',
    reciprocalBehavior: 'automatic',
    sortOrder: 570,
  }),
  relationship({
    key: 'founder',
    displayName: 'Founder',
    aliases: ['founded by'],
    description: 'A Dossier founded another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: ['Location', 'Organization', 'Theory'] as const,
    inverse: 'founded',
    reciprocalBehavior: 'automatic',
    sortOrder: 580,
  }),
  relationship({
    key: 'bonded',
    displayName: 'Bonded',
    aliases: ['bonded pair', 'bondmate'],
    description: 'Two Dossiers share a lore-specific bond.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'bonded',
    reciprocalBehavior: 'automatic',
    sortOrder: 600,
  }),
  relationship({
    key: 'rider',
    displayName: 'Rider',
    aliases: ['dragon rider'],
    description: 'A Character is the rider of a bonded creature or Artifact.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: ['Character', 'Artifact'] as const,
    inverse: 'dragon',
    reciprocalBehavior: 'contextual',
    sortOrder: 610,
  }),
  relationship({
    key: 'dragon',
    displayName: 'Dragon',
    aliases: ['dragon of rider'],
    description: 'A Character or Artifact is the dragon of a rider.',
    directionality: 'directional',
    validSourceTypes: ['Character', 'Artifact'] as const,
    validTargetTypes: characterOnly,
    inverse: 'rider',
    reciprocalBehavior: 'contextual',
    sortOrder: 620,
  }),
  relationship({
    key: 'creator',
    displayName: 'Creator',
    aliases: ['maker'],
    description: 'A Dossier created another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: createdTargets,
    inverse: 'creation',
    reciprocalBehavior: 'automatic',
    sortOrder: 630,
  }),
  relationship({
    key: 'creation',
    displayName: 'Creation',
    aliases: ['created work'],
    description: 'A Dossier was created by another Dossier.',
    directionality: 'directional',
    validSourceTypes: createdTargets,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'creator',
    reciprocalBehavior: 'automatic',
    sortOrder: 640,
  }),
  relationship({
    key: 'owner',
    displayName: 'Owner',
    aliases: ['owns'],
    description: 'A Dossier owns or claims another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'companionOf',
    reciprocalBehavior: 'suggested',
    sortOrder: 650,
  }),
  relationship({
    key: 'companionOf',
    displayName: 'Companion Of',
    aliases: ['owned by', 'possession'],
    description: 'A Dossier is connected as the companion or possession of another Dossier.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'owner',
    reciprocalBehavior: 'suggested',
    sortOrder: 660,
  }),
  relationship({
    key: 'participant',
    displayName: 'Participant',
    aliases: ['participated in', 'attendee'],
    description: 'A Dossier participates in an Event.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: eventTargets,
    inverse: 'hostedEvent',
    reciprocalBehavior: 'automatic',
    sortOrder: 700,
  }),
  relationship({
    key: 'hostedEvent',
    displayName: 'Hosted Event',
    aliases: ['event participant'],
    description: 'An Event includes another Dossier as a participant.',
    directionality: 'directional',
    validSourceTypes: eventTargets,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'participant',
    reciprocalBehavior: 'automatic',
    sortOrder: 710,
  }),
  relationship({
    key: 'occurredAt',
    displayName: 'Occurred At',
    aliases: ['took place at'],
    description: 'An Event occurred at a Location or Organization.',
    directionality: 'directional',
    validSourceTypes: eventTargets,
    validTargetTypes: placeLikeTargets,
    inverse: 'eventAt',
    reciprocalBehavior: 'automatic',
    sortOrder: 720,
  }),
  relationship({
    key: 'eventAt',
    displayName: 'Event At',
    aliases: ['hosted occurrence'],
    description: 'A Location or Organization hosted an Event.',
    directionality: 'directional',
    validSourceTypes: placeLikeTargets,
    validTargetTypes: eventTargets,
    inverse: 'occurredAt',
    reciprocalBehavior: 'automatic',
    sortOrder: 730,
  }),
  relationship({
    key: 'resident',
    displayName: 'Resident',
    aliases: ['resides in', 'inhabitant'],
    description: 'A Character resides in a Location or Organization.',
    directionality: 'directional',
    validSourceTypes: characterOnly,
    validTargetTypes: placeLikeTargets,
    inverse: 'residence',
    reciprocalBehavior: 'automatic',
    sortOrder: 740,
  }),
  relationship({
    key: 'residence',
    displayName: 'Residence',
    aliases: ['home of', 'inhabited by'],
    description: 'A Location or Organization is the residence of a Character.',
    directionality: 'directional',
    validSourceTypes: placeLikeTargets,
    validTargetTypes: characterOnly,
    inverse: 'resident',
    reciprocalBehavior: 'automatic',
    sortOrder: 750,
  }),
  relationship({
    key: 'ruler',
    displayName: 'Ruler',
    aliases: ['rules'],
    description: 'A Character or Organization rules a Location or Organization.',
    directionality: 'directional',
    validSourceTypes: ['Character', 'Organization'] as const,
    validTargetTypes: placeLikeTargets,
    inverse: 'ruledBy',
    reciprocalBehavior: 'automatic',
    sortOrder: 760,
  }),
  relationship({
    key: 'ruledBy',
    displayName: 'Ruled By',
    aliases: ['under rule'],
    description: 'A Location or Organization is ruled by another Dossier.',
    directionality: 'directional',
    validSourceTypes: placeLikeTargets,
    validTargetTypes: ['Character', 'Organization'] as const,
    inverse: 'ruler',
    reciprocalBehavior: 'automatic',
    sortOrder: 770,
  }),
  relationship({
    key: 'memberOf',
    displayName: 'Member Of',
    aliases: ['belongs to'],
    description: 'A Dossier belongs to an Organization.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: ['Organization'] as const,
    inverse: 'organizationMember',
    reciprocalBehavior: 'automatic',
    sortOrder: 780,
  }),
  relationship({
    key: 'organizationMember',
    displayName: 'Organization Member',
    aliases: ['has member'],
    description: 'An Organization has another Dossier as a member.',
    directionality: 'directional',
    validSourceTypes: ['Organization'] as const,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'memberOf',
    reciprocalBehavior: 'automatic',
    sortOrder: 790,
  }),
  relationship({
    key: 'leaderOf',
    displayName: 'Leader Of',
    aliases: ['leads organization'],
    description: 'A Dossier leads an Organization.',
    directionality: 'directional',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: ['Organization'] as const,
    inverse: 'ledBy',
    reciprocalBehavior: 'automatic',
    sortOrder: 800,
  }),
  relationship({
    key: 'ledBy',
    displayName: 'Led By',
    aliases: ['organization led by'],
    description: 'An Organization is led by another Dossier.',
    directionality: 'directional',
    validSourceTypes: ['Organization'] as const,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'leaderOf',
    reciprocalBehavior: 'automatic',
    sortOrder: 810,
  }),
  relationship({
    key: 'founded',
    displayName: 'Founded',
    aliases: ['established'],
    description: 'A Dossier was founded by another Dossier.',
    directionality: 'directional',
    validSourceTypes: ['Location', 'Organization', 'Theory'] as const,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'founder',
    reciprocalBehavior: 'automatic',
    sortOrder: 820,
  }),
  relationship({
    key: 'associatedWith',
    displayName: 'Associated With',
    aliases: ['connected to'],
    description: 'Two Dossiers have a general investigative association.',
    directionality: 'symmetric',
    validSourceTypes: allKnowledgeTypes,
    validTargetTypes: allKnowledgeTypes,
    inverse: 'associatedWith',
    reciprocalBehavior: 'suggested',
    repeatable: true,
    sortOrder: 900,
  }),
] as const satisfies readonly ThreadmarkDefinition[]);

